- name: Frontend setup
  hosts: FRONTEND
  become: yes
  tags: FRONTEND
  roles:
    - frontend

- name: MongoDB setup
  hosts: MONGODB
  become: yes
  tags: MONGODB
  roles:
    - mongodb

- name: Catalogue setup
  hosts: CATALOGUE
  become: yes
  tags: CATALOGUE
  roles:
    - catalogue

- name: Redis setup
  hosts: REDIS
  become: yes
  tags: REDIS
  roles:
    - redis

- name: User setup
  hosts: USER
  become: yes
  tags: USER
  roles:
    - user

- name: Cart setup
  hosts: CART
  become: yes
  tags: CART
  roles:
    - cart

- name: MySQL setup
  hosts: MYSQL
  become: yes
  tags: MYSQL
  roles:
    - mysql

- name: Shipping setup
  hosts: SHIPPING
  become: yes
  tags: SHIPPING
  roles:
    - shipping

- name: RabbitMQ setup
  hosts: RABBITMQ
  become: yes
  tags: RABBITMQ
  roles:
    - rabbitmq

- name: Payment setup
  hosts: PAYMENT
  become: yes
  tags: PAYMENT
  roles:
    - payment

#- name: Dispatch setup
#  hosts: DISPATCH
#  become: yes
#  tags: DISPATCH
#  roles:
#    - dispatch